<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DSH WV2</AssemblyName>
    <RootNamespace>DeepSeekHarness.Desktop</RootNamespace>
    <ApplicationIcon>Assets\whale.ico</ApplicationIcon>
    <Product>DeepSeek Harness Desktop Client - Powered by C#/WPF on WebView2</Product>
    <AssemblyTitle>DSH WV2</AssemblyTitle>
    <Version>1.2.0</Version>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <InformationalVersion>1.2.0</InformationalVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <NoWarn>$(NoWarn);WFAC010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\whale.ico" />
    <Content Include="Assets\whale.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
